# Generated by Django 4.1.7 on 2023-09-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.IntegerField(choices=[(None, 'Vazio'), (0, 'Futsal'), (1, 'Volleyball'), (2, 'Queimado')])),
                ('status', models.IntegerField(choices=[(None, 'Vazio'), (0, 'Em Breve'), (1, 'Acontecendo'), (2, 'Finalizado')])),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='defaults/player.png', upload_to='players/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='defaults/team.png', upload_to='teams/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(None, 'Vazio'), (0, 'Assistência'), (1, 'Gol'), (2, '1 Ponto'), (3, '2 Pontos'), (4, '3 Pontos')])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.players')),
                ('team_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teammatchinfo')),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teams'),
        ),
        migrations.CreateModel(
            name='PlayerModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.IntegerField(choices=[(None, 'Vazio'), (0, 'Futsal'), (1, 'Volleyball'), (2, 'Queimado')])),
                ('position', models.IntegerField(choices=[(None, 'Vazio')])),
                ('activity', models.IntegerField(choices=[(None, 'Vazio'), (0, 'Titular'), (1, 'Reserva')])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.players')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Penalties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(None, 'Vazio'), (0, 'Falta'), (1, 'Cartão Amarelo'), (2, 'Cartão Vermelho')])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.players')),
                ('team_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teammatchinfo')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teams'),
        ),
    ]
