# Generated by Django 4.1.7 on 2023-09-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodality',
            name='position',
            field=models.IntegerField(blank=True, choices=[(None, 'Vazio')], null=True),
        ),
    ]
