# Generated by Django 4.1.7 on 2023-09-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_playermodality_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='team',
        ),
    ]
