# Generated by Django 4.1.7 on 2023-10-01 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_players_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermodality',
            name='position',
        ),
        migrations.AddField(
            model_name='match',
            name='mvp_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.players'),
        ),
        migrations.AddField(
            model_name='players',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermodality',
            name='activity',
            field=models.IntegerField(blank=True, choices=[(None, 'Vazio'), (0, 'Titular'), (1, 'Reserva')], null=True),
        ),
        migrations.AlterField(
            model_name='playermodality',
            name='modality',
            field=models.IntegerField(blank=True, choices=[(None, 'Vazio'), (0, 'Futsal'), (1, 'Volleyball'), (2, 'Queimado')], null=True),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='type',
            field=models.IntegerField(choices=[(None, 'Vazio'), (0, 'Gol'), (1, 'Ponto')]),
        ),
        migrations.CreateModel(
            name='Assistances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assist_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rewards')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.players')),
                ('team_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teammatchinfo')),
            ],
        ),
    ]
