# Generated by Django 4.1.7 on 2023-10-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_playermodality_position_match_mvp_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodality',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(None, 'Vazio'), (0, 'Masculino'), (1, 'Feminino')], null=True),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='type',
            field=models.IntegerField(choices=[(None, 'Vazio'), (0, 'Gol'), (1, 'Ponto'), (2, 'Ace')]),
        ),
    ]
