# Generated by Django 4.1.7 on 2023-10-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_playermodality_sex_alter_rewards_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(None, 'Vazio'), (0, 'Masculino'), (1, 'Feminino')], null=True),
        ),
    ]
