# Generated by Django 4.1.7 on 2023-10-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_volleysets_match_volley_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='volleysets',
            name='status',
            field=models.IntegerField(choices=[(None, 'Vazio'), (0, 'Em Breve'), (1, 'Acontecendo'), (2, 'Finalizado')], default=0),
        ),
    ]
